unset POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB POSTGRES_PORT;
unset PGUSER PGHOST PGPASSWORD PGDATABASE PGPORT;
unset PGADMIN_DEFAULT_EMAIL PG_DEFAULT_PASSWORD PGADMIN_PORT_EXT PGADMIN_PORT_INT;
unset ADMINER_PORT_EXT ADMINER_PORT_INT;

unset SERVNAME_PG SERVNAME_PGADMIN SERVNAME_ADMINER SERVNAME_MIG SERVNAME_WS;

return 0
