version: '3.1'

services:

  db:
    image: postgres:10.12
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  web:
    image: adminer
    restart: always
    ports:
      - 35000:8080