version: '3.1'

services:

  db:
    image: postgres:10.12
    hostname: cmsdb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - default

  web:
    image: adminer
    restart: always
    networks:
      - default
    ports:
      - 35000:8080
      
networks:
  default:
    driver: bridge
