version: '3.5'
services:
  openldap:
    image: cosc425/openldap:1.0.1
    #container_name: ${COMPOSE_PROJECT_NAME}_openldap
    environment:
      LDAP_DOMAIN: "linuxlab.salisbury.edu"
      LDAP_ADMIN_PASSWORD: "password"
      LDAP_ORGINISATION: "Salisbury University"
      LDAP_RFC2307BIS_SCHEMA: "true"
      LDAP_CONFIG_PASSWORD: "password"
      LDAP_LOG_LEVEL: "256"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    #domainname: "openldap" # important: same as hostname
    hostname: "openldap"
    networks:
      - network1
    ports:
      - "5000:389"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    #container_name: ${COMPOSE_PROJECT_NAME}_phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - openldap
    networks:
      - network1
  node:
    image: cosc425/node:1.0.1
    #environment:
    #  public_key: testkey
    #  private_key: testkey2
    hostname: "node"
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    container_name: ${COMPOSE_PROJECT_NAME}_nodejs
    networks:
      - network1
    environment:
      AUTH_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1DNENBUUF3QlFZREsyVndCQ0lFSURDMTkzS2k2WjI0ZzlKNHA4akpuNlZkenVneTBwQWdSOTNHSjdId3d1elIKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
  homedirworker:
    image: cosc425/node:1.0.1
    hostname: "homedirworker"
    environment:
      UMS_ADDRESS: "http://node:80"
      UMS_HOSTNAME: "node:80"
      WORKER_EXTERNAL_ADDRESS: "homedirworker:8081"
      AUTH_TOKEN: v2.public.eyJzdWJqZWN0IjoiYXV0aF90b2tlbiIsImlzc3VlciI6ImhvbWVkaXJxdWV1ZSIsImlhdCI6IjIwMjAtMTEtMThUMjA6MDg6MzAuNzg0WiIsImlzcyI6ImhvbWVkaXJxdWV1ZSIsInN1YiI6ImF1dGhfdG9rZW4ifY29MHiynly3CPEmPSjkclmyO_MGT1U2vji1lPUZk_bnPLf7oeG80MV-c8bar3-KwIBpIyW701DOjH3rSd6Ldwc
    ports:
      - "8081:80"
    volumes:
      - ./homedirworkerapp:/app
      - ./node/TempCPtest:/mnt/home
      - ./node/TempSkel:/mnt/skel
    container_name: ${COMPOSE_PROJECT_NAME}_homedirworker
    networks:
      - network1
networks:
  network1:
    name: network1
