version: '3.5'
services:
  openldap:
    image: cosc425/openldap:1.0.1
    container_name: ${SUDO_USER}_openldap
    networks:
      - network1
    environment:
      LDAP_DOMAIN: "linuxlab.salisbury.edu"
      LDAP_ADMIN_PASSWORD: "password"
      LDAP_ORGINISATION: "Salisbury University"
      LDAP_RFC2307BIS_SCHEMA: "true"
      LDAP_CONFIG_PASSWORD: "password"
      LDAP_LOG_LEVEL: "256"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    #domainname: "openldap" # important: same as hostname
    #hostname: "openldap"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ${SUDO_USER}_phpldapadmin
    networks:
      - network1
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "45679:80"
    depends_on:
      - openldap
networks:
  network1:
    name: ${SUDO_USER}_default