version: '3.5'
services:
  openldap:
    image: cosc425/openldap:1.0.1
    #container_name: ${SUDO_USER}_openldap
    environment:
      LDAP_DOMAIN: "linuxlab.salisbury.edu"
      LDAP_ADMIN_PASSWORD: "password"
      LDAP_ORGANISATION: "Salisbury University"
      LDAP_RFC2307BIS_SCHEMA: "true"
      LDAP_CONFIG_PASSWORD: "password"
      LDAP_LOG_LEVEL: "256"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    #domainname: "openldap" # important: same as hostname
    hostname: "openldap"
    networks:
      - network1
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    #container_name: ${SUDO_USER}_phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - openldap
    networks:
      - network1
  node:
    image: cosc425/node:1.0.1
    hostname: cosc425/node
    volumes: 
      - ./app:/app
    container_name: ${SUDO_USER}_nodejs
    networks:
      - network1    
networks:
  network1:
    name: $NETWORK_NAME